//
//  BibelverseArray.swift
//  BibelSpiel
//
//  Created by Tobias Meisinger on 18.04.20.
//  Copyright © 2020 meitosoft. All rights reserved.
//

import Foundation


func BibelverseArray(spracheID: Int) -> [Bibelvers] {
    
    // schwierigkeitID: 1- einfach, 2- mittel, 3- schwer
    // kategorieID: 1- Bibelverse, 2- Schreiber, 3- Zeitangaben
    // spracheID: 0- deutsch  1- mazedonisch  2- english  3- romani
    
    var bibelverseArray = [Bibelvers]()
    
    if spracheID == 0 {
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 1, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 1, txt: "Am Anfang erschuf Gott Himmel und Erde."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 2, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 8, txt: "Dann kam in Ägypten ein neuer König an die Macht, einer, der Joseph nicht kannte."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 3, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 1, txt: "Falls jemand sündigt, weil er über etwas nicht aussagt, wovon er Zeuge geworden ist oder was er gesehen oder erfahren hat, obwohl er einen öffentlichen Aufruf zur Zeugenaussage gehört hat, dann soll er sich für sein Vergehen verantworten"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 4, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 12, versInt: 3, txt: "Der Mann Moses nun war bei Weitem der sanfteste aller Menschen auf der Erde"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 5, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 30, versInt: 19, txt: "Der Himmel und die Erde sollen heute meine Zeugen sein, dass ich dir Leben und Tod vorgelegt habe, den Segen und den Fluch. Wähle das Leben, damit du am Leben bleibst, du und deine Nachkommen"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 6, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 8, txt: "Entferne dieses Gesetzbuch nicht von deinen Lippen, sondern lies Tag und Nacht mit leiser Stimme darin, damit du dich gewissenhaft an alles hältst, was darin steht. Dann liegt ein erfolgreicher Weg vor dir und dann wirst du weise handeln."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 7, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 16, versInt: 26, txt: "Simson sagte zu dem Jungen, der ihn an der Hand hielt: „Lass mich die Säulen anfassen, die das Haus stützen, damit ich mich dort anlehnen kann.“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 8, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 17, txt: "Wo du stirbst, werde ich sterben, und dort werde ich auch begraben werden. Jehova soll es mir doppelt zurückzahlen, wenn irgendetwas anderes als der Tod uns trennen sollte.“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 9, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 11, txt: "Folgendes Gelübde legte sie ab: „O Jehova, Herr der Heere, wenn du meinen Kummer siehst und an mich, deine Dienerin, denkst und mich nicht vergisst und mir einen männlichen Nachkommen schenkst, dann werde ich ihn dir, Jehova, für sein ganzes Leben überlassen. Kein Schermesser wird seinen Kopf berühren.“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 10, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 3, txt: "Alle Ältesten Israels kamen also zum König nach Hẹbron und dort schloss König David mit ihnen vor Jehova einen Bund. Sie salbten David dann zum König von Israel."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 11, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 12, txt: "Sạlomo setzte sich dann auf den Thron seines Vaters David und seine Königsherrschaft wurde allmählich gefestigt."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 12, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 22, versInt: 1, txt: "Josịa wurde mit acht Jahren König und regierte 31 Jahre in Jerusalem. Seine Mutter hieß Jedịda und war die Tochter von Adạja aus Bọzkath."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 13, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 15, versInt: 29, txt: "Als die Bundeslade Jehovas in der Stadt Davids ankam, schaute Sauls Tochter Mịchal aus dem Fenster hinunter und sah, wie König David herumhüpfte und feierte. Von da an verachtete sie ihn in ihrem Herzen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 14, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 36, versInt: 21, txt: "So sollte sich erfüllen, was Jehova durch Jeremia angekündigt hatte, bis das Land seine Sabbate abgezahlt hatte. Solange es öde und verlassen war, hielt es Sabbat, bis 70 Jahre voll waren."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 15, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 1, txt: "Im ersten Jahr des Königs Cyrus von Persien sollte sich erfüllen, was Jehova durch Jeremia angekündigt hatte. Darum bewog Jehova König Cyrus von Persien dazu, durch sein ganzes Reich einen Aufruf ergehen zu lassen, den er auch schriftlich festhielt. Er lautete:"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 16, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 4, txt: "Der König erwiderte: „Was ist deine Bitte?“ Sofort betete ich zum Gott des Himmels."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 17, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 8, versInt: 2, txt: "Der König zog seinen Siegelring ab, den er Hạman weggenommen hatte, und gab ihn Mọrdechai. Esther machte Mọrdechai zum Verwalter von Hạmans Haus."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 18, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 42, versInt: 5, txt: "Meine Ohren haben von dir gehört, aber jetzt sehe ich dich mit eigenen Augen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 19, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 83, versInt: 18, txt: "Die Menschen sollen wissen, dass du, dessen Name Jehova ist, du allein, der Höchste bist über die ganze Erde."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 20, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 27, versInt: 11, txt: "Sei weise, mein Sohn, und mach meinem Herzen Freude, damit ich dem, der mich verhöhnt, eine Antwort geben kann."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 21, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 12, versInt: 1, txt: "Denk also an deinen großen Schöpfer in deiner Jugend, bevor die beschwerlichen Tage kommen und sich die Jahre einstellen, von denen du sagen wirst: „Sie gefallen mir gar nicht“,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 22, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 1, txt: "„Wie schön du bist, meine Geliebte! Wie schön du bist! Deine Augen hinter deinem Schleier sind wie die von Tauben. Dein Haar gleicht einer Ziegenherde, die von den Bergen Gịleads herabzieht."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 23, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 11, versInt: 6, txt: "Der Wolf wird sich bei dem Lamm aufhalten, der Leopard wird neben dem Ziegenjungen liegen und das Kalb und der Löwe und das gut genährte Tier werden alle beieinander sein. Und ein kleiner Junge wird sie führen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 24, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 10, versInt: 5, txt: "Wie eine Vogelscheuche in einem Gurkenfeld können solche Götzen nicht reden. Man muss sie tragen, denn sie können nicht laufen. Habt keine Angst vor ihnen, denn sie können keinen Schaden anrichten, und Gutes können sie auch nicht tun.“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 25, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 8, txt: "Jerusalem hat schwer gesündigt. Deshalb ist sie zu etwas Abscheulichem geworden. Alle, die sie früher ehrten, behandeln sie jetzt verächtlich, denn sie haben ihre Nacktheit gesehen. Sie selbst seufzt und wendet sich aus Scham ab."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 26, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 18, versInt: 4, txt: "Alle Seelen — mir gehören sie. Wie die Seele des Vaters so auch die Seele des Sohnes — mir gehören sie. Die Seele, die sündigt, sie wird sterben."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 27, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 8, txt: "Daniel beschloss jedoch in seinem Herzen, sich nicht mit den Delikatessen und dem Wein des Königs zu verunreinigen. Er bat den obersten Hofbeamten also um Erlaubnis, sich nicht auf diese Weise verunreinigen zu müssen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 28, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 1, txt: "Dann sagte Jehova zu mir: „Geh noch einmal und liebe die Frau, die von einem anderen Mann geliebt wird und Ehebruch begeht, so wie Jehova das Volk Israel liebt, während es sich anderen Göttern zuwendet und Rosinenkuchen liebt.“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 29, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 15, txt: "O weh, was für ein Tag! Denn der Tag Jehovas ist nah und er wird kommen wie eine Zerstörung durch den Allmächtigen!"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 30, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 15, txt: "Hasst das Schlechte und liebt das Gute, sorgt für Gerechtigkeit im Stadttor. Es kann sein, dass Jehova, der Gott der Heere, den Übriggebliebenen Josephs Gunst schenkt.‘"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 31, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 4, txt: "Selbst wenn du dich hoch oben niederlässt wie der Adler oder dein Nest bei den Sternen baust, hole ich dich von dort herunter“, erklärt Jehova."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 32, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 11, txt: "Sollte es mir dann nicht auch leidtun um Nịnive, die große Stadt, in der mehr als 120 000 Menschen leben, die nicht einmal zwischen Richtig und Falsch unterscheiden können, und noch dazu ihre vielen Tiere?“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 33, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 2, txt: "Und du, Bẹthlehem-Ẹphratha, das zu klein ist, um unter die Städte Judas gerechnet zu werden, aus dir wird für mich der hervorgehen, der Herrscher in Israel sein soll, dessen Ursprung aus ferner Zeit ist, aus längst vergangenen Tagen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 34, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 3, txt: "Jehova wird nicht schnell zornig und hat große Macht, doch auf keinen Fall hält Jehova die gebührende Strafe zurück. Im zerstörerischen Wind und im Sturm geht er seinen Weg und die Wolken sind der Staub unter seinen Füßen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 35, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 3, txt: "Denn die Vision wird sich erst zu ihrer festgelegten Zeit erfüllen und sie eilt dem Ende entgegen, sie wird sich nicht als Lüge erweisen. Selbst wenn sie auf sich warten lassen sollte, warte geduldig auf sie! Denn sie wird sich auf jeden Fall erfüllen. Sie wird sich nicht verspäten!"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 36, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 18, txt: "Weder ihr Silber noch ihr Gold wird sie an dem Tag retten, an dem Jehovas Zorn ausbricht, denn das Feuer seines Eifers wird die ganze Erde verzehren. Er wird nämlich alle Bewohner der Erde ausrotten, ja es wird schrecklich sein.“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 37, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 7, txt: "‚Ich werde alle Völker erschüttern und das Wertvolle aus allen Völkern wird hereinkommen. Ich werde dieses Haus mit Herrlichkeit füllen‘, sagt Jehova, der Herr der Heere."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 38, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 8, versInt: 23, txt: "Das sagt Jehova, der Herr der Heere: ‚In jenen Tagen werden zehn Männer aus allen Sprachen der Völker nach dem Gewand eines Juden greifen, ja sie werden es festhalten und sagen: „Wir wollen mit euch gehen, denn wir haben gehört, dass Gott an eurer Seite ist.“ ‘ “"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 39, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 10, txt: "Bringt den ganzen Zehnten ins Vorratshaus, damit Nahrung in meinem Haus ist, und stellt mich so bitte auf die Probe“, sagt Jehova, der Herr der Heere, „und seht, ob ich euch nicht die Schleusen des Himmels öffnen und Segen über euch ausschütten werde, bis es an nichts mehr fehlt.“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 40, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 28, versInt: 19, txt: "Darum geht und macht Menschen aus allen Völkern zu meinen Jüngern, tauft sie im Namen des Vaters und des Sohnes und des heiligen Geistes,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 41, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 14, versInt: 51, txt: "Nur ein junger Mann folgte ihm in einiger Entfernung. Er trug lediglich ein Gewand aus feinem Leinen auf dem bloßen Leib, und als man ihn packen wollte,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 42, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 3, txt: "Also habe auch ich beschlossen, diese Fakten in logischer Reihenfolge für dich, hochverehrter Theọphilus, aufzuschreiben. Ich bin nämlich allem von Anfang an genau nachgegangen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 43, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 11, versInt: 11, txt: "Dann fügte er noch hinzu: „Unser Freund Lạzarus ist eingeschlafen, aber ich gehe jetzt hin, um ihn zu wecken.“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 44, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 29, txt: "Petrus und die anderen Apostel erwiderten: „Wir müssen Gott als Herrscher gehorchen statt Menschen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 45, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 6, versInt: 23, txt: "Denn der Lohn, den die Sünde zahlt, ist der Tod, doch das Geschenk, das Gott gibt, ist ewiges Leben durch Christus Jesus, unseren Herrn."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 46, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 9, txt: "Denn wir sind Gottes Mitarbeiter. Ihr seid Gottes Feld, das bebaut wird, Gottes Bauwerk."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 47, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 6, versInt: 14, txt: "Bildet kein ungleiches Gespann mit Ungläubigen. Denn wie gehören Gerechtigkeit und Gesetzlosigkeit zusammen? Oder was hat Licht mit Finsternis zu tun?"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 48, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 6, versInt: 7, txt: "Lasst euch nicht täuschen: Gott lässt sich nicht verspotten. Was immer jemand sät, das wird er auch ernten."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 49, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 16, txt: "und macht das Beste aus eurer Zeit, denn die Zeiten sind schlimm."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 50, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 6, txt: "Macht euch um nichts Sorgen, sondern lasst Gott in allem durch Gebet und Flehen zusammen mit Dank wissen, was eure Bitten sind."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 51, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 2, txt: "Hört nicht auf zu beten, bleibt dabei wach und sagt Dank."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 52, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 3, txt: "Wann immer sie sagen: „Frieden und Sicherheit!“, dann wird plötzlich Vernichtung über sie hereinbrechen wie Geburtswehen über eine Schwangere, und sie werden auf keinen Fall entkommen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 53, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 6, txt: "Es ist nämlich gerecht von Gott, dass er denen, die euch Drangsal bereiten, mit Drangsal zurückzahlt."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 54, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 1, txt: "Vor allem bitte ich nun dringend, dass im Hinblick auf Menschen aller Art Flehen, Gebete, Fürbitten und Dank dargebracht werden,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 55, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 15, txt: "Tu dein Möglichstes, um vor Gott bewährt dazustehen, als ein Arbeiter, der sich wegen nichts zu schämen braucht, der das Wort der Wahrheit richtig handhabt."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 56, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 8, txt: "Diese Worte sind zuverlässig, und ich möchte, dass du das alles immer wieder betonst, damit sich die, die zum Glauben an Gott gekommen sind, darauf konzentrieren, stets Gutes zu tun. Diese Dinge sind gut und nützen den Menschen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 57, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 4, txt: "Ich danke meinem Gott immer, wenn ich dich in meinen Gebeten erwähne,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 58, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 12, txt: "Das Wort Gottes ist lebendig und übt Macht aus. Es ist schärfer als jedes zweischneidige Schwert und dringt sogar so weit durch, dass es Seele und Geist trennt und Gelenke vom Mark. Es kann Gedanken und Absichten des Herzens beurteilen."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 59, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 8, txt: "Wenn ihr nun das königliche Gesetz befolgt, das in der Schriftstelle enthalten ist: „Du sollst deinen Mitmenschen lieben wie dich selbst“, ist das gut so."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 60, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 14, txt: "Wenn man euch wegen des Namens Christi beleidigt, seid ihr glücklich, weil der Geist der Herrlichkeit, ja der Geist Gottes, auf euch ruht."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 61, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 9, txt: "Jehova ist nicht langsam, wenn es um sein Versprechen geht, wie manche meinen, sondern er ist geduldig mit euch, weil er nicht will, dass irgendjemand vernichtet wird, sondern dass alle zur Reue finden."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 62, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 8, txt: "Wer Sünde treibt, stammt vom Teufel, denn der Teufel hat von Anfang an gesündigt. Dazu ist der Sohn Gottes offenbart worden: um das, was der Teufel getan hat, zu zerstören."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 63, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 10, txt: "Wenn jemand zu euch kommt und diese Lehre nicht vertritt, dann nehmt ihn weder in euer Haus auf noch grüßt ihn."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 64, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 5, txt: "Lieber Freund, du beweist deine Treue durch das, was du für die Brüder tust, obwohl du sie nicht kennst."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 65, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 21, txt: "So bleibt ihr in Gottes Liebe, während ihr mit der Aussicht auf ewiges Leben auf die Barmherzigkeit unseres Herrn Jesus Christus wartet."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 66, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 21, versInt: 4, txt: "Und er wird jede Träne von ihren Augen abwischen, und den Tod wird es nicht mehr geben. Auch wird es weder Trauer noch Aufschrei noch Schmerz mehr geben. Was früher war, ist vorbei.“"))

        
    } else if spracheID == 1 {
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 1, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 1, txt: "Во почетокот Бог ги создаде небото и земјата."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 2, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 8, txt: "Со текот на времето, над Египет завладеа нов цар кој не го познаваше Јосиф."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 3, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 1, txt: "Ако некој згреши така што чул јавна клетва, а не сака да открие што видел како сведок или што знае за тоа, ќе одговара за својот престап."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 4, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 12, versInt: 3, txt: "А Мојсеј беше многу кроток човек, најкроткиот од сите луѓе на земјата"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 5, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 30, versInt: 19, txt: "Ги земам денес за сведоци против вас небото и земјата: дека пред вас ставам живот и смрт, благослов и проклетство. Затоа избери го животот за да останеш жив, ти и твоето потомство,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 6, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 8, txt: "Оваа книга на законот нека не ти се одделува од устата! Внимателно читај ја дење и ноќе за да го правиш совесно сето она што е запишано во неа, зашто тогаш ќе бидеш успешен на својот пат и ќе постапуваш мудро."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 7, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 16, versInt: 26, txt: "Тогаш Самсон му рече на момчето што го водеше за рака: „Пушти ме да ги напипам столбовите врз кои стои оваа зграда и да се потпрам на нив“."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 8, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 17, txt: "Каде ќе умреш ти, таму ќе умрам и јас, и таму ќе бидам погребана. Јехова нека ми направи така, и уште нека ми додаде, ако ме оддели од тебе нешто друго освен смртта“."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 9, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 11, txt: "И вака се заветува: „Јехова над војските, ако погледнеш на неволјата на својата робинка и ако се сетиш на мене, ако не ја заборавиш својата робинка и ако ѝ дадеш машко дете на својата робинка, јас ќе ти го дадам тебе, Јехова, за сите денови од неговиот живот, и брич нема да помине преку неговата глава“."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 10, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 3, txt: "Така сите старешини на Израел дојдоа кај царот во Хеврон, и цар Давид склучи со нив сојуз во Хеврон пред Јехова. Потоа го помазаа Давид за цар на Израел."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 11, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 12, txt: "И Соломон седна на престолот на Давид, својот татко, и неговото царство многу се зацврсти."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 12, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 22, versInt: 1, txt: "Јосија имаше осум години кога почна да владее и владееше триесет и една година во Ерусалим. Мајка му се викаше Једида и беше ќерка на Адаија од Васкат."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 13, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 15, versInt: 29, txt: "А кога ковчегот на Јеховиниот сојуз влегуваше во Давидовиот град, Сауловата ќерка Михала гледаше низ прозорецот и го виде цар Давид како потскокнува и се весели. И го презре во своето срце."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 14, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 36, versInt: 21, txt: "за да се исполни речта која Јехова ја објави преку устата на Еремија, додека земјата не ги надомести своите одмори. Земјата одмораше во сите денови додека беше пуста, додека не се навршија седумдесет години."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 15, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 1, txt: "Во првата година на Кир, персискиот цар, за да се исполни Јеховината реч објавена преку устата на Еремија, Јехова го поттикна срцето на персискиот цар Кир, па тој нареди да се објави следново и усно и писмено, по целото негово царство:"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 16, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 4, txt: "А царот ми одговори: „Значи, што бараш?“ Во тој час му се помолив на небесниот Бог,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 17, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 8, versInt: 2, txt: "Тогаш царот го извади својот печатен прстен, кој му го беше одзел на Аман, па му го даде на Мардохеј, а Естира го постави Мардохеј над куќата на Аман."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 18, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 42, versInt: 5, txt: "Досега те знаев од слушање, но сега моето око те гледа."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 19, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 83, versInt: 18, txt: "за да се знае дека единствено ти, чие име е Јехова, си Севишен над целата земја!"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 20, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 27, versInt: 11, txt: "Биди мудар, сине мој, и израдувај ми го срцето, за да можам да му одговорам на оној што ми се подбива."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 21, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 12, versInt: 1, txt: "Сеќавај се на својот Величествен Творец во деновите на младоста своја, пред да дојдат зли денови и пред да пристигнат годините за кои ќе речеш: „Не ми се мили“;"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 22, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 1, txt: "„Колку си убава, о љубена моја! Колку си убава! Очите ти се како на гулабица под превезот твој. Косата ти е како стадо кози што потскокнуваат надолу по ридовите галадски."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 23, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 11, versInt: 6, txt: "Волкот ќе живее со јагнето, леопардот ќе лежи со јарето, телето и младиот лав и згоеното животно ќе бидат заедно, а мало дете ќе ги води."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 24, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 10, versInt: 5, txt: "Тие се како страшило во нива со краставици, не можат да зборуваат. Треба да ги носат, зашто не можат да одат. Не плашете се од нив, зашто не можат да направат никакво зло, а камоли нешто добро!“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 25, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 8, txt: "Тешко згреши Ерусалим. Затоа стана одвратен. Сите што го почитуваа сега го потценуваат, бидејќи ја видоа неговата голотија. А и тој самиот воздивнува и го врти грбот."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 26, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 18, versInt: 4, txt: "Гледај, сите души ми припаѓаат мене. Душата на таткото и душата на синот ми припаѓа мене. Онаа душа што греши, таа и ќе умре."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 27, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 8, txt: "Но Даниел одлучи во своето срце да не се извалка со избраните царски јадења и со виното што го пиеше царот. Затоа повеќе пати го молеше главниот дворјанин да го поштеди за да не се извалка."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 28, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 1, txt: "Потоа Јехова ми рече: „Оди и повторно сакај ја жената која друг ја сака и која врши прељуба, како што Јехова ги сака синовите на Израел, додека тие се свртуваат кон други богови и со задоволство им принесуваат суво грозје“."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 29, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 15, txt: "Леле, каков ден! Зашто, денот Јеховин е близу, доаѓа како опустошување од Семоќниот!"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 30, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 15, txt: "Мразете го злото, а сакајте го доброто, и дајте ѝ место на правдата при градската порта! Можеби Јехова, Богот над војските, ќе му се смилува на Јосифовиот остаток‘."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 31, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 4, txt: "Ако се сместиш високо како орел или ако го направиш своето гнездо меѓу ѕвездите, и оттаму ќе те соборам“, вели Јехова."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 32, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 11, txt: "А мене да не ми биде жал за Ниневија, голем град, во кој има повеќе од сто и дваесет илјади луѓе, кои не знаат што е десно, а што лево, а покрај тоа и многу стока?“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 33, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 2, txt: "А ти, Витлееме Ефрато, кој си најмал од Јудините градови, од тебе ќе ми излезе оној што ќе биде владетел во Израел, кој потекнува од дамнини, од прадамнешните денови."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 34, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 3, txt: "Јехова е бавен на гнев и има огромна моќ. Јехова нема да се воздржува да казни. Во разорен ветар и во бура е патот негов, а облаците се како прав под нозете негови."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 35, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 3, txt: "Зашто, тоа видение ќе се исполни во времето што е одредено за него. Видението брза кон крајот и нема да излаже. Дури и да се забави, чекај го, зашто бездруго ќе се исполни. Нема да задоцни."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 36, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 18, txt: "Ни нивното сребро ни нивното злато не ќе може да ги избави во денот на Јеховиниот гнев. Огнот на неговата ревност ќе ја проголта целата земја, зашто тој со страшно истребување ќе ги истреби сите што живеат на земјата.“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 37, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 7, txt: "‚Ќе ги затресам сите народи, и ќе дојдат скапоценостите од сите народи, и ќе го наполнам овој дом со слава‘, вели Јехова над војските."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 38, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 8, versInt: 23, txt: "Вака вели Јехова над војските: ‚Во тие денови, десет луѓе од сите јазици што ги зборуваат народите ќе фатат за скут еден Евреин, ќе го фатат, велејќи: „Ќе одиме со вас зашто чувме дека Бог е со вас“ ‘ “."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 39, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 10, txt: "Донесете ги сите десеттини во складиштето, па да има храна во мојот дом, и испитајте ме во тоа, ве молам,“ вели Јехова над војските, „зар нема да ви ги отворам небесните брани и да ви излеам благослов додека не биде доста?“"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 40, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 28, versInt: 19, txt: "Затоа одете и правете ученици од луѓето од сите народи, крштавајќи ги во името на Таткото и на Синот и на светиот дух,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 41, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 14, versInt: 51, txt: "А по него одеше едно момче, облечено само во ленена облека. И се обидоа да го фатат,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 42, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 3, txt: "па и јас, честити Теофиле, откако внимателно испитав сѐ од почетокот, решив да ти напишам тебе сѐ по ред,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 43, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 11, versInt: 11, txt: "Тоа го кажа, а потоа додаде: „Нашиот пријател Лазар заспа, но јас одам да го разбудам“."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 44, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 29, txt: "Тогаш Петар и другите апостоли рекоа: „Мораме да му се покоруваме на Бог, а не на луѓето."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 45, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 6, versInt: 23, txt: "Зашто, платата за гревот е смрт, а дарот што го дава Бог е вечен живот преку Христос Исус, нашиот Господар."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 46, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 9, txt: "Зашто, ние сме Божји соработници, а вие сте Божја нива, Божја градба."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 47, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 6, versInt: 14, txt: "Не впрегнувајте се во нееднаков јарем со неверници. Зашто, што им е заедничко на праведноста и на беззаконието? Или какво заедништво има светлината со темнината?"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 48, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 6, versInt: 7, txt: "Не залажувајте се: со Бог нема подигрување! Човек што ќе си посее, тоа и ќе си пожнее."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 49, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 16, txt: "Откупувајте си време, зашто деновите се зли."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 50, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 6, txt: "Не бидете загрижени за ништо, туку во сѐ — со молитви и молби, со благодарење — изнесете му ги своите барања на Бог."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 51, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 2, txt: "Истрајте во молитвата, бдејте во неа и благодарете."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 52, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 5, versInt: 3, txt: "Кога ќе зборуваат: „Мир и сигурност!“ — тогаш ненадејно ќе ги снајде уништување како како што ја снаоѓаат родилни болки бремена жена, и нема да побегнат."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 53, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 6, txt: "Зашто, праведно е Бог да им ја врати неволјата на оние што ви нанесуваат неволја,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 54, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 1, txt: "Затоа, пред сѐ, поттикнувам да се упатуваат барања, молитви, молби и благодарења за најразлични луѓе,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 55, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 15, txt: "Дај сѐ од себе за да стекнеш признание од Бог, да бидеш работник кој нема од што да се срами, кој исправно се служи со речта на вистината."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 56, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 8, txt: "Веродостојно е ова што е речено и сакам тоа постојано да го застапуваш, за оние што поверувале во Бог да се сосредоточат на правењето на добри дела. Тоа е добро и корисно за луѓето."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 57, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 4, txt: "Секогаш му благодарам на својот Бог кога те спомнувам во молитвите"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 58, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 12, txt: "Зашто, речта Божја е жива и делотворна, поостра е од секој меч со две сечила и продира дури дотаму што ги разделува душата и духот, коските и нивната срцевина, па може да ги процени мислите и намерите на срцето."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 59, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 2, versInt: 8, txt: "Значи, ако го исполнувате царскиот закон, според зборовите од Писмото: „Сакај го својот ближен како себеси“, добро правите."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 60, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 4, versInt: 14, txt: "Ако ве исмејуваат поради Христовото име, среќни сте, бидејќи духот на славата — духот Божји — почива врз вас."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 61, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 9, txt: "Јехова не доцни со исполнувањето на своето ветување, како што некои мислат дека доцни, туку е стрплив со вас бидејќи не сака никој да биде уништен, туку сите да дојдат до покајание."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 62, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 3, versInt: 8, txt: "Кој оди во грев, потекнува од Ѓаволот, бидејќи Ѓаволот греши откако се побуни. Затоа дојде Синот Божји, да ги уништи делата на Ѓаволот."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 63, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 10, txt: "Ако некој дојде кај вас и не го носи тоа учење, не примајте го во својот дом, ниту поздравувајте го."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 64, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 5, txt: "Сакан, твојата верност се гледа во сѐ што правиш за браќата, и тоа за оние што не ги познаваш,"))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 65, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 1, versInt: 21, txt: "стојте во Божјата љубов додека го чекате милосрдието на нашиот Господар Исус Христос и се надевате на вечниот живот."))
        bibelverseArray.append(createBibelvers(reihenfolgeNr: 66, schwierigkeitID: 1, kategorieID: 0, kapitelInt: 21, versInt: 4, txt: "И тој ќе ја избрише секоја солза од нивните очи и смрт нема да има веќе, ни тага, ни пискот, ниту болка. Сѐ што беше порано, помина“."))
        
    }
    
    
    return bibelverseArray
}


func createBibelvers(reihenfolgeNr: Int, schwierigkeitID: Int, kategorieID: Int, kapitelInt: Int, versInt: Int, txt: String) -> Bibelvers {
    
    var bibelvers = Bibelvers()
    bibelvers.reihenfolgeNr = reihenfolgeNr
    bibelvers.schwierigkeitID = schwierigkeitID
    bibelvers.kategorieID = kategorieID
    bibelvers.kapitelInt = kapitelInt
    bibelvers.versInt = versInt
    bibelvers.txt = txt
    
    return bibelvers
}
